### ISSUE TITLE
java.io.FileNotFoundException: config (Is a directory)

### ISSUE THREAD

**Issue by cliffordwolf** [ucb-bar/riscv-torture#2] opened 2016-02-10 15:56 UTC
According to the README file running `./sbt generator/run` should generate a single test case. However, here it generates the following error message (this is in a pristine working copy):

```
[info] Loading project definition from /home/clifford/Temp/riscv-torture/project
[info] Updating {file:/home/clifford/Temp/riscv-torture/project/}riscv-torture-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /home/clifford/Temp/riscv-torture/project/target/scala-2.10/sbt-0.13/classes...
[warn] there were 1 deprecation warning(s); re-run with -deprecation for details
[warn] one warning found
[info] Set current project to torture (in build file:/home/clifford/Temp/riscv-torture/)
[info] Updating {file:/home/clifford/Temp/riscv-torture/}generator...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 24 Scala sources to /home/clifford/Temp/riscv-torture/generator/target/scala-2.11/classes...
[warn] there was one deprecation warning; re-run with -deprecation for details
[warn] one warning found
[info] Running torture.generator.Generator 
[error] (run-main-0) java.io.FileNotFoundException: config (Is a directory)
java.io.FileNotFoundException: config (Is a directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at java.io.FileInputStream.<init>(FileInputStream.java:101)
    at torture.generator.Generator$.generate(main.scala:31)
    at torture.generator.Generator$.main(main.scala:23)
    at torture.generator.Generator.main(main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last generator/compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last generator/compile:run for the full output.
[error] (generator/compile:run) Nonzero exit code: 1
[error] Total time: 29 s, completed Feb 10, 2016 4:41:56 PM
```

`config` indeed is a directory. It is part of the repository. the only mention of `config` in the `strace -f` output is this:

```
14643 open("config", O_RDONLY)          = 80
14643 fstat(80, {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
14643 close(80)                         = 0
```

So it does open the config directory, checks if the fd is connected to a file, and then closes it again right away. It never tries to open any of the files in `config/`.

Running something like `./sbt generator/run -C config/default.config` instead does not make any difference. I still get the `java.io.FileNotFoundException: config (Is a directory)` error.

Am I doing something wrong?

**Comment by ccelio** [comment] 2016-02-10 22:00
> Running something like ./sbt generator/run -C config/default.config instead does not make any difference. I still get the java.io.FileNotFoundException: config (Is a directory) error.
> 
> Am I doing something wrong?

This is not obvious, but the proper way to feed your Scala program command line options when invoked via `sbt` is this:

```
./sbt 'generator/run -C config/default.config'
```

Which yields the correct behavior. 

---

But more to your issue...

Sorry, this error was introduced by making `config` no longer a file, but a directory to contain an entire set of config files. The issue is that I failed to update `generator/src/main/scala/main.scala`'s default `config` file.  

[Ed: the reason I missed this is that we use torture through the Makefile (via `testrun` and `overnight`) and thus never directly invoke generator in a manner that relies on its default `configFileName`. Whoops.]

Fix is incoming...

**Closed as completed** 2016-02-10 22:05 UTC
